site_name: ZeroDiff
site_description: ZeroDiff Documentation
site_author: Jeff Williams
site_url: https://zerodiff.org/
watch:
  - docs
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Software:
    - software/index.md
  - Hardware:
    - hardware/index.md
    - Beginners:
        - Overview: hardware/beginners/overview.md
        - Kaizen/CPI: hardware/beginners/kaizen.md
        - Design: hardware/beginners/design.md
        - User Editable Doc Repo: hardware/beginners/user_docs.md
        - All Designs To Github: hardware/beginners/doc_control.md
        - EE Checklist: hardware/hardware/pcb_checklist.md
        - Firmware Checklist: hardware/firmware/checklist.md
        - CI Server: hardware/beginners/tdd_ci.md
    - Design:
        - User Empathy: hardware/design/empathy.md
        - First Principles: hardware/design/essential_user_task.md
        - Make Fewer Things: hardware/design/fewer.md
        - Teach, Don't Lead: hardware/design/teach.md
        - What's Testable?: hardware/design/testable.md
        - Ethnographic Study: hardware/design/ethno_study.md
        - Design Sprint: hardware/design/sprint.md
    - Hardware:
        - Top-Level Object Dev: hardware/hardware/top_level.md
        - PCB/A:
            - PCB/A Dev: hardware/hardware/pcba.md
            - Release CheckList: hardware/hardware/pcb_checklist.md
        - MechE:
            - MechE Dev: hardware/hardware/mech_eng.md
            - Release CheckList: hardware/hardware/meche_checklist.md
            - Test Criteria: hardware/hardware/mech_eng_test.md
            - Process Improvement: hardware/hardware/process_improvement.md
        - Firmware:
            - Firmware Dev: hardware/firmware/dev.md
            - Release Checklist: hardware/firmware/checklist.md
        - Vendors:
            - Trust as a Tool: hardware/vendor/trust.md
            - Assembly, Fab Notes: hardware/vendor/fab.md
            - ECOs - Yes, No, Maybe: hardware/vendor/eco.md
    - Test:
        - Automated Monkey Tests: hardware/test/monkey.md
  - Glossary: glossary.md
  - About:
      - Overview: about/overview.md
      - Why ZeroDiff?: about/why.md
      - Contribute: about/contribute.md
      - License: about/license.md

theme:
  name: material
  custom_dir: theme-overrides
  favicon: icons/favicon.ico
  logo: icons/zerodiff.svg
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  language: en
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
#    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
#    - toc.integrate

plugins:
  - blog:
      enabled: true
      post_date_format: medium
      blog_toc: true
      archive: true
      archive_date_format: MMMM yyyy
#      post_count: 1
  - search:
      lang: en
  - redirects:
      redirect_maps: {}
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enabled: false
      enable_creation_date: false
      type: date
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zero-diff
      name: ZeroDiff on GitHub
    - icon: material/rss
      link: /feed_rss_created.xml
      name: Zerodiff RSS feed
  analytics:
    provider: google
    property: G-6Q7FXB2D6X

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_url: https://github.com/zero-diff/zerodiff/
repo_name: zero-diff/zerodiff

copyright: >
  <a href="https://zerodiff.org">ZeroDiff Blog</a><br>
  Copyright &copy; 2020-2026 <a href="https://github.com/0x6a77">Jeff Williams</a> under BSD-3 License

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascript/extra.js